// Code generated by nanostack/generator; DO NOT EDIT.

package testmodel

type PersonBuilder struct {
	instance *Person
}

func NewPersonBuilder() *PersonBuilder {
	return &PersonBuilder{instance: &Person{}}
}
func (p *Person) ToBuilder() *PersonBuilder {
	if p == nil {
		return NewPersonBuilder()
	}
	return &PersonBuilder{instance: &Person{Name: p.Name, Age: p.Age}}
}
func (b *PersonBuilder) WithName(name string) *PersonBuilder {
	b.instance.Name = name
	return b
}
func (b *PersonBuilder) WithAge(age int) *PersonBuilder {
	b.instance.Age = age
	return b
}
func (b *PersonBuilder) Build() *Person {
	return b.instance
}
